apiVersion: kartverket.dev/v1alpha1
kind: Function
metadata:
  name: Test2
  description: ""
  links:
    - url: ""
      title: ""
spec:
  owner: SKVIS
  criticality: Middels
  childFunctions:
    - test21
  dependsOn: []
