apiVersion: kartverket.dev/v1alpha1
kind: Function
metadata:
  name: Test2.1
  description: ""
  links:
    - url: ""
      title: ""
    - url: ""
      title: ""
    - url: ""
      title: ""
spec:
  owner: SKVIS
  criticality: Lav
  childFunctions: []
  dependsOn: []
