apiVersion: kartverket.dev/v1alpha1
kind: Function
metadata:
  name: Test2.1
  description: ""
spec:
  owner: SKVIS
  criticality: Lav
  childFunctions: []
  dependsOn: []
  dependsOnSystems:
    - system:default/utviklerportal
  dependsOnComponents:
    - component:default/security-champion-service
  parentFunction: function:default/Test2
